# Generated by Django 5.2.9 on 2026-01-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_revise_coupon_model'),
        ('enrollments', '0004_add_history_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_types',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='historicalcoupon',
            name='discount_types',
        ),
        migrations.RemoveField(
            model_name='historicalcoupon',
            name='discount_value',
        ),
        migrations.AddField(
            model_name='coupon',
            name='admission_fee_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to deduct from admission fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Leave empty to apply to all courses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='first_month_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional discount for the first month only', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public coupons are shown in the list during enrollment'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='offer_message',
            field=models.CharField(blank=True, help_text="Promotional message shown to parents (e.g., '50% off admission fee!')", max_length=255),
        ),
        migrations.AddField(
            model_name='coupon',
            name='tuition_fee_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to deduct from monthly tuition fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalcoupon',
            name='admission_fee_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to deduct from admission fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalcoupon',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Leave empty to apply to all courses', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.course'),
        ),
        migrations.AddField(
            model_name='historicalcoupon',
            name='first_month_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional discount for the first month only', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalcoupon',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public coupons are shown in the list during enrollment'),
        ),
        migrations.AddField(
            model_name='historicalcoupon',
            name='offer_message',
            field=models.CharField(blank=True, help_text="Promotional message shown to parents (e.g., '50% off admission fee!')", max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcoupon',
            name='tuition_fee_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to deduct from monthly tuition fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, help_text='Internal description for admin reference'),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='description',
            field=models.TextField(blank=True, help_text='Internal description for admin reference'),
        ),
    ]
