# Generated by Django 5.2.9 on 2026-01-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_revise_coupon_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcoupon',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
