# Generated by Django 5.1.6 on 2025-02-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tuition_fee',
            new_name='monthly_fee',
        ),
    ]
