# Generated by Django 5.2.9 on 2026-01-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_tuition_fee_course_monthly_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_available',
            field=models.BooleanField(default=False, help_text='Whether discount/offer is currently available'),
        ),
        migrations.AddField(
            model_name='course',
            name='offer_text',
            field=models.CharField(blank=True, help_text="Promotional text to display (e.g., '50% off admission fee!')", max_length=255),
        ),
    ]
