# Generated by Django 5.2.9 on 2026-01-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_discount_fields'),
        ('enrollments', '0004_add_history_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discount_available',
        ),
        migrations.RemoveField(
            model_name='course',
            name='offer_text',
        ),
        migrations.AddField(
            model_name='course',
            name='featured_coupon',
            field=models.ForeignKey(blank=True, help_text='Public coupon to display as promotional offer on this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_on_courses', to='enrollments.coupon'),
        ),
    ]
