# Generated by Django 5.1.6 on 2025-02-25 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('payments', '0002_payment_payer_reference_payment_payment_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='enrollments.enrollment'),
        ),
    ]
