# Generated by Django 5.1.6 on 2025-02-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_invoice_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='temp_invoice',
            field=models.BooleanField(default=False, help_text='Whether this is a temporary invoice for enrollment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='temp_invoice_data',
            field=models.JSONField(blank=True, help_text='Temporary enrollment data for webhook processing', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
