# Generated by Django 5.1.6 on 2025-02-28 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_coupon_discount_value'),
        ('payments', '0004_invoice_temp_invoice_invoice_temp_invoice_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollments.coupon'),
        ),
    ]
