# Generated by Django 5.1.6 on 2025-02-15 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=11)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('provider_response', models.JSONField(null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sms_logs',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ACCOUNT_CREATION', 'Account Creation'), ('ENROLLMENT', 'Student Enrollment'), ('PAYMENT', 'Payment'), ('COURSE_MODIFICATION', 'Course Modification'), ('BATCH_MODIFICATION', 'Batch Modification'), ('FEE_MODIFICATION', 'Fee Modification'), ('BATCH_TRANSFER', 'Batch Transfer'), ('REMINDER_SENT', 'Payment Reminder Sent')], max_length=50)),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
    ]
