# Generated by Django 5.1.6 on 2025-02-28 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'SMS Log', 'verbose_name_plural': 'SMS Logs'},
        ),
        migrations.RemoveField(
            model_name='smslog',
            name='provider_response',
        ),
        migrations.RemoveField(
            model_name='smslog',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='smslog',
            name='retry_count',
        ),
        migrations.AddField(
            model_name='smslog',
            name='api_response',
            field=models.JSONField(blank=True, help_text='Response from the SMS gateway API', null=True),
        ),
        migrations.AddField(
            model_name='smslog',
            name='failed_count',
            field=models.IntegerField(default=0, help_text='Number of failed deliveries'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='message_type',
            field=models.CharField(choices=[('OTP', 'OTP Verification'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('ENROLLMENT_CONFIRMATION', 'Enrollment Confirmation'), ('CUSTOM', 'Custom Message'), ('BULK', 'Bulk Message')], default='CUSTOM', max_length=25),
        ),
        migrations.AddField(
            model_name='smslog',
            name='phone_number',
            field=models.CharField(default='01212121212', help_text='Recipient phone number(s). For bulk SMS, this will contain the first few recipients.', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smslog',
            name='recipient_count',
            field=models.IntegerField(default=1, help_text='Number of recipients for bulk messages'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated sending the SMS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_sms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smslog',
            name='successful_count',
            field=models.IntegerField(default=0, help_text='Number of successful deliveries'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='message',
            field=models.TextField(help_text='Content of the SMS message'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL_SUCCESS', 'Partial Success'), ('PENDING', 'Pending'), ('DISABLED', 'Disabled')], default='PENDING', max_length=20),
        ),
    ]
